postgres:
  dsn:
    host: db
    port: 5432
    user: postgres
    password: postgres
    db_name: stands
    sslmode: disable
  max_idle_conns: 10
  max_open_conns: 30
  use_seed: true
bot:
  commands:
    list: "List all stands"
    claim: "Claim a stand"
    release: "Release a stand"
    ping: "Ping current stand owner by username"
  token: tokenFromENV
  stands: [dev, dev4, staging]
  verbose: true