postgres:
  dsn:
    host: db
    port: 5432
    user: postgres
    password: postgres
    db_name: stands
    sslmode: disable
  max_idle_conns: 5
  max_open_conns: 5
  use_seed: true
  
bot:
  # set true if debug mode needed for bot
  verbose: true

gitlab:
  token: tokenFromEnv
  url: https://gitlab.com
  project_id: 12345678
  group_id: 00123